### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by heropoo** [Yanlong-LI/php-zero-value#1]
看完源代码有一些建议:
1. 希望可以做成一个工具，此工具用来检查已经写好的类代码，对于未初始化的类属性给予0值修改建议。
2. 如果对于上面的提示能通过脚本去自动修改或者待用户确认后修改，那么应该会更好。
3. 对于一些属性是其他类的情况，在不清楚依赖的情况下还是不要直接new这个类名，避免一些无法预知的问题。

上面都是些个人建议，希望作者能做的更好。

**Comment by yanlong-li** [comment]
根据建议，已增加简单扫描工具，给出文件路径及行号，具体属性信息

```
/workspace/php/zero_value/example/scan_example/Example1.php
      行:13
            源:public Example2 $a;
````
